//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PARRHITests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PARRHITests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--This is the full file with all values specified--&gt;
        ///&lt;InputData xmlns=&quot;PARRHI&quot;&gt;
        ///	&lt;Variables&gt;
        ///		&lt;Int name=&quot;var1&quot;&gt;0&lt;/Int&gt;
        ///	&lt;/Variables&gt;
        ///	&lt;Points&gt;
        ///		&lt;PointRobot name=&quot;Point1&quot; J1=&quot;0&quot; J2=&quot;1&quot; Scale=&quot;0&quot; /&gt;
        ///		&lt;PointRobot name=&quot;Point2&quot; J1=&quot;1&quot; J2=&quot;2&quot; Scale=&quot;0&quot; /&gt;
        ///		&lt;PointRobot name=&quot;Point3&quot; J1=&quot;2&quot; J2=&quot;3&quot; Scale=&quot;0&quot; /&gt;
        ///		&lt;PointRobot name=&quot;Point4&quot; J1=&quot;3&quot; J2=&quot;4&quot; Scale=&quot;0&quot; /&gt;
        ///		&lt;PointRobot name=&quot;Point5&quot; J1=&quot;4&quot; J2=&quot;5&quot; Scale=&quot;0&quot; /&gt;
        ///		&lt;PointRobot name=&quot;Point6&quot; J1=&quot;5&quot; J2=&quot;5&quot; Scale=&quot;0&quot; /&gt;
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inputxml {
            get {
                return ResourceManager.GetString("inputxml", resourceCulture);
            }
        }
    }
}
