using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace PARRHI.Objects
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Dieser Code wurde von einem Tool generiert.
    //     Laufzeitversion:4.0.30319.42000
    //
    //     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
    //     der Code erneut generiert wird.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.7.2053.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "PARRHI", IsNullable = false)]
    public partial class InputData
    {

        /// <remarks/>
        public InputDataVariables Variables;

        /// <remarks/>
        public InputDataPoints Points;

        /// <remarks/>
        public InputDataHolograms Holograms;

        /// <remarks/>
        public InputDataEvents Events;

        /// <remarks/>
        public InputDataUIText UIText;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataVariables
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Int")]
        public InputDataVariablesInt[] Int;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataVariablesInt
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public byte Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataPoints
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PointCamera", typeof(InputDataPointsPointCamera))]
        [System.Xml.Serialization.XmlElementAttribute("PointFix", typeof(InputDataPointsPointFix))]
        [System.Xml.Serialization.XmlElementAttribute("PointRobot", typeof(InputDataPointsPointRobot))]
        public object[] Items;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataPointsPointCamera
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataPointsPointFix
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal X;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Y;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Z;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataPointsPointRobot
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte J1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte J2;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Scale;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataHolograms
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sphere", typeof(InputDataHologramsSphere))]
        [System.Xml.Serialization.XmlElementAttribute("Zylinder", typeof(InputDataHologramsZylinder))]
        public object[] Items;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataHologramsSphere
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string point;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte radius;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataHologramsZylinder
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string point1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string point2;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte radius;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataEvents
    {

        /// <remarks/>
        public InputDataEventsTrigger Trigger;

        /// <remarks/>
        public InputDataEventsActions Actions;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataEventsTrigger
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TimeTrigger")]
        public InputDataEventsTriggerTimeTrigger[] TimeTrigger;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DistanceTrigger")]
        public InputDataEventsTriggerDistanceTrigger[] DistanceTrigger;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VarTrigger")]
        public InputDataEventsTriggerVarTrigger[] VarTrigger;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataEventsTriggerTimeTrigger
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool canTrigger;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte timeSinceActivation;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action2;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataEventsTriggerDistanceTrigger
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool canTrigger;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string point1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string point2;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal distance;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action2;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataEventsTriggerVarTrigger
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool canTrigger;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string varName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte triggerValue;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action2;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataEventsActions
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChangeUITextAction", typeof(InputDataEventsActionsChangeUITextAction))]
        [System.Xml.Serialization.XmlElementAttribute("IncrementCounterAction", typeof(InputDataEventsActionsIncrementCounterAction))]
        [System.Xml.Serialization.XmlElementAttribute("MoveRobotAction", typeof(InputDataEventsActionsMoveRobotAction))]
        [System.Xml.Serialization.XmlElementAttribute("SetRobotHandStateAction", typeof(InputDataEventsActionsSetRobotHandStateAction))]
        [System.Xml.Serialization.XmlElementAttribute("SetTriggerStateAction", typeof(InputDataEventsActionsSetTriggerStateAction))]
        public object[] Items;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataEventsActionsChangeUITextAction
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataEventsActionsIncrementCounterAction
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string intVar;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataEventsActionsMoveRobotAction
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pointTCP;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataEventsActionsSetRobotHandStateAction
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataEventsActionsSetTriggerStateAction
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string triggerName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool canTrigger;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "PARRHI")]
    public partial class InputDataUIText
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text;
    }

}
